### ISSUE TITLE
issues with autorole upon target level

### ISSUE THREAD

**Issue by xXxCake2019xXx** [aikaterna/Fixator10-Cogs#4]
When a role is linked to a level so when the user reaches that level they get given a role. it doesn't update their roles at all even when the role level was reached. 

no clue what could be causing this the bot has all permissions and the user is someone who just joined a few days ago and reached the target level by chatting. so everything should be going fine just no idea on how to go about fixing this.

**Comment by aikaterna** [comment]
The recent commits I did and Kenny did for leveler should have resolved your issues. I can't double check as the image links you provided for your errors in the cog server have expired or are not available any more. Please open another issue with more information, like traceback text, if you still have issues after this. Thanks.
